config/routes.rb
Rails.application.routes.draw do

  get 'images/new'
  get "upload", to: "images#new"
  get 'images/edit'
  get 'images/update'
  get 'images/destroy'
  get 'images/index'
  get 'images/show'
  

  get "categories/index", to: "categories#index"

  resources :images
  resources :categories

  root "images#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :images

  validates :name, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :category

  mount_uploader :image, ImageUploader

  before_save :update_image_attributes

  private
    def update_image_attributes
      if image.present? && image_changed?
        self.image_content_type = image.file.content_type
        self.image_file_size = image.file.size
      end
      #code
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_categories
  def set_categories
    @categories = Category.all
    #code
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    #code
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category added"
      redirect_to categories_path
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
    @images = @category.images.all
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to category_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  def show
    @category = Category.find(params[:id])
    @images = @category.images.all
  end

  private
    def category_params
      params.require(:category).permit(:name)
      #code
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:edit, :update, :show, :destroy]

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:notice] = "Image added"
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
    @image.update(image_params)
    redirect_to root_path
  end

  def destroy
    @category = @image.category
    @image.destroy
    flash[:alert] = "Image deleted"
    redirect_to edit_category_path(@category)
  end

  def index
    @images = Image.all
  end

  def show
  end

  private
    def set_image
      @image = Image.find(params[:id])
      #code
    end

    def image_params
      params.require(:image).permit(:image_title, :category_id, :image_description, :image, :image_file_size, :image_content_type)
      #code
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/categories/edit.html.erb
<h2>Edit category</h2>

<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "Cancel", categories_path, class: "btn btn-secondary" %>
<% end %>
<br /><br />

<h3 class="page-header">Images in <%= @category.name %></h3>
<div id="edit_images">
  <% if @images.exists? %>
    <% @images.each_slice(6) do |image| %>
      <div class="row">
        <% image.each do |image| %>
          <div class="col-md-2">
            <%= image_tag image.image_url(:thumb) %>
            <center><%= link_to "Delete", image_path(image), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %></center>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <p>No images in this category</p>
  <% end %>
</div>

app/views/categories/index.html.erb
<h2>Categories</h2>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Category name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <% @categories.each do |category| %>
    <tr>
      <td>
        <%= category.name %>
      </td>
      <td>
        <%= link_to "Edit", edit_category_path(category), class: "btn btn-success" %> <%= link_to "Delete", category_path(category), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"}  %>
      </td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h2>Add new category</h2>

<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "Cancel", categories_path, class: "btn btn-secondary" %>
<% end %>

app/views/categories/show.html.erb
<div id="gallery">
  <h2><%= @category.name %><small class="float-right"><%= link_to "Edit Category", edit_category_path(@category), class: "btn btn-success" %></small></h2>
  <% if @images.exists? %>
    <% @images.each_slice(4) do |image| %>
      <div class="row">
        <% image.each do |image| %>
          <div class="col-md-3">
            <div class="photo photo-type-line">
              <a href="<%= image.image_url %>" class="photo-hover" data-lightbox="my-images" data-title="<%= image.image_title %>">
                <div class="photo-info">
                  <div class="headline">
                    <%= image.image_title %>
                  </div>
                  <div class="line"></div>
                  <div class="desc">
                    <%= image.image_description %>
                  </div>
                </div>
                <div class="mask"></div>
              </a>
              <div class="photo-img"><%= image_tag image.image_url(:thumb)%></div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <% else %>
      <p>There are no images to show</p>
  <% end %>
</div>

app/views/images/edit.html.erb
<h1>Images#edit</h1>
<p>Find me in app/views/images/edit.html.erb</p>

app/views/images/index.html.erb
<div id="gallery">
  <h2>All Images</h2>
  <% if @images.exists? %>
    <% @images.each_slice(4) do |image| %>
      <div class="row">
        <% image.each do |image| %>
          <div class="col-md-3">
            <div class="photo photo-type-line">
              <a href="<%= image.image_url %>" class="photo-hover" data-lightbox="my-images" data-title="<%= image.image_title %>">
                <div class="photo-info">
                  <div class="headline">
                    <%= image.image_title %>
                  </div>
                  <div class="line"></div>
                  <div class="desc">
                    <%= image.image_description %>
                  </div>
                </div>
                <div class="mask"></div>
              </a>
              <div class="photo-img"><%= image_tag image.image_url(:thumb)%></div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <% else %>
      <p>There are no images to show</p>
  <% end %>
</div>

app/views/images/new.html.erb
<h2>Add new image</h2>

<%= form_for @image, html: {multipart: true} do |f| %>
  <% if @image.errors.any? %>
    <% @image.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :image_title %>
    <%= f.text_field :image_title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {include_blank: "Select one"}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image_description %>
    <%= f.text_area :image_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>


  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "Cancel", images_path, class: "btn btn-secondary" %>
<% end %>

app/views/images/show.html.erb
<h1>Images#show</h1>
<p>Find me in app/views/images/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rgallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <%= link_to "rGallery", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <% @categories.each do |category| %>
            <li class="nav-item">
              <%= link_to category.name, category_path(category), class: "nav-link" %>
            </li>
          <% end %>
        </ul>
        <ul class="navbar-nav pull-right">
          <li class="nav-item">
            <%= link_to "Upload photo", new_image_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Category", new_category_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

    <section>
      <div class="container">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <% if flash[:alert] %>
          <div class="alert alert-danger">
            <%= flash[:alert] %>
          </div>
        <% end %>

        <%= yield %>
      </div>
      <!-- /.container -->
    </section>
  </body>
</html>